[package]
name = "totp"
version = "0.1.0"
edition = "2024"
description = "Decoder for TOTP URIs"
license = "MIT"

[workspace]
resolver = "3"
members = [
    "cli",
]

[dependencies]
hmac = "0.12"

[lib]
name = "totp"
path = "src/lib.rs"
